version: 2.0
jobs:
 Hello-World:
   docker:
     - image: alpine:3.7
   steps:
     - run:
         name: Hello World
         command: |
           echo 'Hello World!'
           echo 'This is the delivery pipeline'
           apt-get install --assume-yes git
           git clone https://github.com/msisler99/circleci-terraform.git
           ls -la
 
workflows:
 version: 2
 Example_Workflow:
   jobs:
     - Hello-World
     
