version: 2.0
jobs:
 Hello-World:
   docker:
     - image: hashicorp/terraform:0.11.7
   steps:
     - run:
         name: Hello World
         command: |
           echo 'Hello World!'
           echo 'This is the delivery pipeline'
          
           git clone https://github.com/msisler99/circleci-services.git
           pwd
           ls -la
           cat main.tf
 
workflows:
 version: 2
 Example_Workflow:
   jobs:
     - Hello-World
     
