version: 2.0
jobs:
 PR_Test:
   docker:
     - image: hashicorp/terraform:0.11.7
   steps:
     - run:
         name: PR_Test
         command: |
           git clone https://github.com/msisler99/circleci-services.git
           cd circleci-services
           ls -la
           echo "${CI_PULL_REQUEST}" > temp1.txt
            
           sed 's/^.\{19\}//' temp1.txt > temp2.txt
            
           #sed -e "s/GENERIC/$(sed 's:/:\\/:g' PR_Test)/" backend.tf.save > backend.tf
           sed 's/GENERIC/PR_Test/g' backend.tf.save > backend.tf
           
           cat backend.tf
           
           terraform init
           terraform workspace delete PR_Test
           #terraform workspace new PR_Test
           
           #terraform plan
           
           #terraform apply -auto-approve
           
           #terraform show
           
           #terraform destroy -auto-approve.   
 
workflows:
 version: 2
 Example_Workflow:
   jobs:
     - PR_Test
     
