version: 2.0
jobs:
 Hello-World:
   docker:
     # image: alpine:3.7
     - image: hashicorp/terraform:0.11.7
   steps:
     - run:
         name: Hello World
         command: |
           echo 'Hello World!'
           echo 'This is the delivery pipeline'
           mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

           git clone https://github.com/msisler99/circleci-terraform.git
           cd circleci-terraform
           ls -la
 
workflows:
 version: 2
 Example_Workflow:
   jobs:
     - Hello-World
     
